In [11]:
! pip install scikit-learn

In [12]:
import numpy as np

In [13]:
from sklearn.datasets import load_iris

In [14]:
iris = load_iris()

In [15]:
type(iris)

sklearn.utils._bunch.Bunch

In [16]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Cr

In [17]:
X = iris.data
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [18]:
y = iris.target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [19]:
from tensorflow.keras.utils import to_categorical

In [20]:
y = to_categorical(y)

In [21]:
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [22]:
y.shape

(150, 3)

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [25]:
from sklearn.preprocessing import MinMaxScaler

In [26]:
scaler_obj = MinMaxScaler()
scaler_obj.fit(X_train)

MinMaxScaler()

In [27]:
scaled_X_train = scaler_obj.transform(X_train)

In [28]:
scaled_X_test = scaler_obj.transform(X_test)

In [29]:
type(scaled_X_train)

numpy.ndarray

In [30]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [31]:
model = Sequential()
model.add(Dense(8, input_dim=4, activation='relu'))
model.add(Dense(8, input_dim=4, activation='relu'))
model.add(Dense(3, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [32]:
model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 8)                 40        
                                                                 
 dense_1 (Dense)             (None, 8)                 72        
                                                                 
 dense_2 (Dense)             (None, 3)                 27        
                                                                 
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [33]:
model.fit(scaled_X_train,y_train,epochs=500, verbose=2)

Epoch 1/500
4/4 - 1s - loss: 1.5366 - accuracy: 0.3100 - 938ms/epoch - 235ms/step
Epoch 2/500
4/4 - 0s - loss: 1.5131 - accuracy: 0.3000 - 6ms/epoch - 2ms/step
Epoch 3/500
4/4 - 0s - loss: 1.4886 - accuracy: 0.2900 - 7ms/epoch - 2ms/step
Epoch 4/500
4/4 - 0s - loss: 1.4678 - accuracy: 0.2800 - 6ms/epoch - 2ms/step
Epoch 5/500
4/4 - 0s - loss: 1.4465 - accuracy: 0.2600 - 6ms/epoch - 2ms/step
Epoch 6/500
4/4 - 0s - loss: 1.4250 - accuracy: 0.2100 - 6ms/epoch - 1ms/step
Epoch 7/500
4/4 - 0s - loss: 1.4074 - accuracy: 0.1500 - 7ms/epoch - 2ms/step
Epoch 8/500
4/4 - 0s - loss: 1.3892 - accuracy: 0.0800 - 9ms/epoch - 2ms/step
Epoch 9/500
4/4 - 0s - loss: 1.3743 - accuracy: 0.0500 - 4ms/epoch - 1ms/step
Epoch 10/500
4/4 - 0s - loss: 1.3595 - accuracy: 0.0000e+00 - 8ms/epoch - 2ms/step
Epoch 11/500
4/4 - 0s - loss: 1.3457 - accuracy: 0.0000e+00 - 6ms/epoch - 2ms/step
Epoch 12/500
4/4 - 0s - loss: 1.3321 - accuracy: 0.0000e+00 - 7ms/epoch - 2ms/step
Epoch 13/500
4/4 - 0s - loss: 1.3194 - accura

In [34]:
prediction_classes = np.argmax(model.predict(scaled_X_test), axis=1)
prediction_classes

2/2 [==============================] - 0s 10ms/step


array([1, 0, 2, 1, 1, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 1, 2, 1, 2], dtype=int64)

In [35]:
model.metrics_names

['loss', 'accuracy']

In [36]:
model.evaluate(x=scaled_X_test,y=y_test)

2/2 [==============================] - 0s 10ms/step - loss: 0.2687 - accuracy: 0.9600


[0.2686767280101776, 0.9599999785423279]

In [37]:
from sklearn.metrics import confusion_matrix,classification_report

In [38]:
confusion_matrix(y_test.argmax(axis=1), prediction_classes)

array([[19,  0,  0],
       [ 0, 14,  1],
       [ 0,  1, 15]], dtype=int64)

In [39]:
print(classification_report(y_test.argmax(axis=1), prediction_classes))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.93      0.93      0.93        15
           2       0.94      0.94      0.94        16

    accuracy                           0.96        50
   macro avg       0.96      0.96      0.96        50
weighted avg       0.96      0.96      0.96        50



In [71]:
# model.save('iris_deep_nn_model.h5')

In [73]:
# Loading the model
from tensorflow.keras.models import load_model
iris_model = load_model('iris_deep_nn_model.h5')

In [83]:
y_pred = np.argmax(iris_model.predict(scaled_X_test), axis=1)

2/2 [==============================] - 0s 6ms/step


In [85]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test.argmax(axis=1), y_pred)

0.96