In [15]:
! pip install scikit-learn

   ---------------------------------------- 0.0/11.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.1 MB ? eta -:--:--
   - -------------------------------------- 0.5/11.1 MB 3.4 MB/s eta 0:00:04
   ------- -------------------------------- 2.1/11.1 MB 5.3 MB/s eta 0:00:02
   --------------- ------------------------ 4.2/11.1 MB 7.4 MB/s eta 0:00:01
   --------------------- ------------------ 6.0/11.1 MB 7.9 MB/s eta 0:00:01
   ---------------------------- ----------- 7.9/11.1 MB 8.0 MB/s eta 0:00:01
   --------------------------------- ------ 9.4/11.1 MB 8.0 MB/s eta 0:00:01
   ---------------------------------------- 11.1/11.1 MB 8.1 MB/s eta 0:00:00


In [17]:
import numpy as np

In [19]:
from sklearn.datasets import load_iris

In [21]:
iris = load_iris()

In [23]:
type(iris)

sklearn.utils._bunch.Bunch

In [25]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Cr

In [27]:
X = iris.data
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [29]:
y = iris.target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [31]:
from tensorflow.keras.utils import to_categorical

In [33]:
y = to_categorical(y)

In [35]:
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [37]:
y.shape

(150, 3)

In [41]:
from sklearn.model_selection import train_test_split

In [43]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [45]:
from sklearn.preprocessing import MinMaxScaler

In [47]:
scaler_obj = MinMaxScaler()
scaler_obj.fit(X_train)

MinMaxScaler()

In [49]:
scaled_X_train = scaler_obj.transform(X_train)

In [51]:
scaled_X_test = scaler_obj.transform(X_test)

In [53]:
type(scaled_X_train)

numpy.ndarray

In [55]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [57]:
model = Sequential()
model.add(Dense(8, input_dim=4, activation='relu'))
model.add(Dense(8, input_dim=4, activation='relu'))
model.add(Dense(3, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [59]:
model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 8)                 40        
                                                                 
 dense_1 (Dense)             (None, 8)                 72        
                                                                 
 dense_2 (Dense)             (None, 3)                 27        
                                                                 
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [73]:
model.fit(scaled_X_train,y_train,epochs=500, verbose=2)

Epoch 1/500
4/4 - 0s - loss: 0.4628 - accuracy: 0.7100 - 17ms/epoch - 4ms/step
Epoch 2/500
4/4 - 0s - loss: 0.4616 - accuracy: 0.7100 - 9ms/epoch - 2ms/step
Epoch 3/500
4/4 - 0s - loss: 0.4607 - accuracy: 0.6900 - 6ms/epoch - 2ms/step
Epoch 4/500
4/4 - 0s - loss: 0.4598 - accuracy: 0.7000 - 9ms/epoch - 2ms/step
Epoch 5/500
4/4 - 0s - loss: 0.4584 - accuracy: 0.7200 - 9ms/epoch - 2ms/step
Epoch 6/500
4/4 - 0s - loss: 0.4575 - accuracy: 0.7300 - 8ms/epoch - 2ms/step
Epoch 7/500
4/4 - 0s - loss: 0.4563 - accuracy: 0.7300 - 9ms/epoch - 2ms/step
Epoch 8/500
4/4 - 0s - loss: 0.4555 - accuracy: 0.7300 - 10ms/epoch - 3ms/step
Epoch 9/500
4/4 - 0s - loss: 0.4540 - accuracy: 0.7300 - 10ms/epoch - 2ms/step
Epoch 10/500
4/4 - 0s - loss: 0.4532 - accuracy: 0.7400 - 8ms/epoch - 2ms/step
Epoch 11/500
4/4 - 0s - loss: 0.4521 - accuracy: 0.7400 - 10ms/epoch - 2ms/step
Epoch 12/500
4/4 - 0s - loss: 0.4511 - accuracy: 0.7400 - 8ms/epoch - 2ms/step
Epoch 13/500
4/4 - 0s - loss: 0.4500 - accuracy: 0.7400 -

In [91]:
prediction_classes = np.argmax(model.predict(scaled_X_test), axis=1)
prediction_classes

2/2 [==============================] - 0s 14ms/step


array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 1, 2, 1, 2], dtype=int64)

In [93]:
model.metrics_names

['loss', 'accuracy']

In [95]:
model.evaluate(x=scaled_X_test,y=y_test)

2/2 [==============================] - 0s 4ms/step - loss: 0.1349 - accuracy: 0.9800


[0.13493825495243073, 0.9800000190734863]

In [97]:
from sklearn.metrics import confusion_matrix,classification_report

In [99]:
confusion_matrix(y_test.argmax(axis=1), prediction_classes)

array([[19,  0,  0],
       [ 0, 15,  0],
       [ 0,  1, 15]], dtype=int64)

In [103]:
print(classification_report(y_test.argmax(axis=1), prediction_classes))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.94      1.00      0.97        15
           2       1.00      0.94      0.97        16

    accuracy                           0.98        50
   macro avg       0.98      0.98      0.98        50
weighted avg       0.98      0.98      0.98        50

